### ISSUE TITLE
Time-varying weights

### ISSUE THREAD

**Issue by jimioke** [mboeck11/BGVAR#1]
We are currently looking into using your nicely documented package for a GVAR modeling application. Wondering however if there were any plans in the works to add capability for time-varying weights... or looking to see whether this is something that could be readily contributed from my end here. Just wanted to post this, in case it was something you were already looking at.

**Comment by mboeck11** [comment]
Just for clarification: do you have weights for each point in time in your dataset?

**Comment by jimioke** [comment]
@mboeck11 Sorry for the late revert - did not check back quicker for a response. Yes - exactly - weights for each point in time, such that we would have a $W_t$ for each timestep $t$ instead of just a static $W$.

**Comment by mboeck11** [comment]
Right now it's unfortunately not implemented, but in principle it but requires quite some in-depth changes in the code. I'll definitely put it on the list for the next update, and right now I only can offer you to use a static weight matrix. Nevertheless, you can play around using different weight matrices in different specifications. In economic applications weight matrices are often only available in a five-year interval while the data frequency is quarterly. Hence, people just check whether results change with different weight matrices as robustness check.

**Comment by jimioke** [comment]
Thanks for the response. Yes - the application we are attempting is a bit more dynamic in nature (compared to the typical macroeconomic situations). I will check back to see whenever updates are made, but we will also try to see if this can be implemented on our end, and if this can be successfully done, we hope we can contribute to the package. Again, great work!
