### ISSUE TITLE
Unit and scaling in irf

### ISSUE THREAD

**Issue by 88312** [mboeck11/BGVAR#15]
Hi, I'm wondering if the unit in the irf function could be clarified.
The tutorial (vignettes/examples.html) says it adjusts the scale of an irf by "shockinfo_chol$scale<--100" "for a negative 100 bp shock applied to US short term interest rates:"
However, the stir data in eerData, which is used in the tutorial, are not in bp. Also, the s.e. of the short term interest rates does not happen to be 1 bp.
So, it seems that the scaling is not correct. The responses of the variables in "Responses of US country model" figure looks indeed too big for a 100 bp shock.

I guess the unit of a shock in the irf function is the same as the data. Is this correct?

**Comment by mboeck11** [comment]
Thank you for pointing this out - 100 basis points correspond here to -1 not -100! We've corrected this in the new version.
