### ISSUE TITLE
Question on the default prior mean for the NG prior

### ISSUE THREAD

**Issue by marahem** [mboeck11/BGVAR#28]
Hi,

First, I would like to sincerely thank you for sharing your excellently documented code and package, as well as for continuously keeping it updated.

I have some questions about the default value of the prior mean when selecting the NG prior (prior="NG") and using hyperpara=NULL.

The documentation states that all unit-specific coefficients have a Normal prior distribution with the following prior mean:

> "Prior mean on the first lag of the autoregressive coefficients, standard value is prmean=1 for non-stationary data. Prior mean for the remaining autoregressive coefficients automatically set to 0."

However, after reviewing lines 409–417 in BGVAR.R, it appears to me that the default value is prmean=0.

So, assuming prior="NG" and using hyperpara=NULL, my questions are:

1. Does the default prior mean for the first own lag coefficients always default to 1, as the documentation suggests, or does the code detect non-stationarity and adjust accordingly (e.g., 1 for non-stationary and 0 otherwise)? In other words, what is the actual default Normal prior mean, and does this single prmean value apply to **all** own lag coefficients?

2. If I manually set prmean=0.8 in the hyperpara list, does this override the default behavior and apply prmean=0.8 to **all** own first lag coefficients?

3. Is my understanding correct that the prior mean for cross-lag coefficients and own lags beyond the first lag is always set to zero, similar to a standard Minnesota prior?

Sorry for the lengthy and somewhat repetitive message, and thank you for your time.

**Comment by mboeck11** [comment]
Hi,

Thanks for raising this issue (and the nice feedback!). Thanks for pointing this out, the documentation is wrong here. Reason is that this automatic check was once implemented but had erroraneous behavior, unfortunately. It seems that I've never updated the documentation in this regard.

So regarding your questions. Before answering them, this does not hold only for the NG prior but for the remaining priors as well.

1. The default value for the prior mean is set to zero. This value applies to all own lag coefficients.
2. If you manually set prmean to a specific value, you override the default value.
3. The argument 'prmean' applies only to own first lags, no other prior means (e.g., cross-lag coefficients or own lags beyond the first one). So exactly as in the standard Minnesota prior case.

I'll update the documentation, which will then be included in the next update of the package. Thanks again for pointing this out.
